version: "3"

services:

  web:
    build: .
    command: bash -c "python manage.py migrate &&
      exec gunicorn netology_pd_diplom.wsgi:application -b 0.0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=netology_shp
      - DB_PASSWORD=postgres
    depends_on:
      - redis
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres
    environment:
      - POSTGRES_DB=netology_shp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/usr/src/app/postgresql
  celery:
    restart: always
    build: .
    command: celery -A netology_pd_diplom worker -B -l INFO
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_NAME=netology_shp
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis
      - web
  redis:
    image: redis
    ports:
      - "6379:6379"
